name: Ejercicio 1 - Accion Docker

on:
  push:
    branches: [main]

jobs:
  correr-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Usar accion Docker
        uses: ./ejercicio-1-docker 
